{% set name = "opentelemetry-instrumentation-marqo" %}
{% set version = "0.40.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_marqo-{{ version }}.tar.gz
  sha256: 7648271294e9bebf1fc8d97753a3d4aad841a7e0965c7a2b1f8200cd30112ac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions-ai 0.4.9
  run_constrained:
    - marqo >=3.5.1,<4.0.0

test:
  imports:
    - opentelemetry.instrumentation.marqo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - marqo

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Marqo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
