{% set name = "opentelemetry-instrumentation-marqo" %}
{% set version = "0.47.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_marqo-{{ version }}.tar.gz
  sha256: e7c6fd11d14d102f7aeaa25e9f643cb7189ae2b29add8a00da130733d62b7859

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5
  run_constrained:
    - marqo >=3.5.1,<4.0.0

test:
  imports:
    - opentelemetry.instrumentation.marqo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - marqo

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Marqo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
